import { cn } from '@/lib/utils';
import { ArrowRight, Check, AlertTriangle, Quote, Calculator, Lightbulb, List } from 'lucide-react';

/**
 * Layout hints generated by AI during slide creation
 * The AI analyzes content semantically to determine optimal visual presentation
 */
export interface LayoutHint {
  type: 'flow' | 'comparison' | 'equation' | 'list' | 'quote' | 'callout' | 'plain';
  segments?: string[];           // For flows: ["Step 1", "Step 2", "Step 3"]
  left_right?: [string, string]; // For comparisons: ["Vision", "Mission"]
  formula?: string;              // For equations: "ROI = (Gain - Cost) / Cost"
  emphasis_words?: string[];     // Words to highlight
}

export interface ContentBlockProps {
  text: string;
  layoutHint?: LayoutHint;
  isActive?: boolean; // For audio sync highlighting
  blockId?: string;
  className?: string;
}

/**
 * Render text with emphasis on specific words
 */
function renderWithEmphasis(text: string, emphasisWords?: string[]): React.ReactNode {
  if (!emphasisWords?.length) return text;

  // Create regex pattern for all emphasis words (case-insensitive)
  const pattern = new RegExp(`\\b(${emphasisWords.map(w => w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})\\b`, 'gi');
  const parts = text.split(pattern);

  return parts.map((part, i) => {
    const isEmphasis = emphasisWords.some(w => w.toLowerCase() === part.toLowerCase());
    return isEmphasis ? (
      <strong key={i} className="text-primary font-semibold">{part}</strong>
    ) : (
      <span key={i}>{part}</span>
    );
  });
}

/**
 * Flow layout: horizontal steps with arrows
 */
function FlowBlock({ segments, emphasisWords, isActive }: { 
  segments: string[]; 
  emphasisWords?: string[];
  isActive?: boolean;
}) {
  return (
    <div className={cn(
      "flex flex-wrap items-center gap-2 p-4 rounded-lg bg-gradient-to-r from-primary/5 to-primary/10 border border-primary/20",
      isActive && "ring-2 ring-primary/50 bg-primary/15"
    )}>
      {segments.map((segment, i) => (
        <div key={i} className="flex items-center gap-2">
          <div className="flex items-center gap-2 px-4 py-2 rounded-full bg-background border shadow-sm">
            <span className="w-6 h-6 rounded-full bg-primary/20 flex items-center justify-center text-xs font-bold text-primary">
              {i + 1}
            </span>
            <span className="font-medium text-sm">
              {renderWithEmphasis(segment, emphasisWords)}
            </span>
          </div>
          {i < segments.length - 1 && (
            <ArrowRight className="h-5 w-5 text-primary/60 flex-shrink-0" />
          )}
        </div>
      ))}
    </div>
  );
}

/**
 * Comparison layout: side-by-side cards
 */
function ComparisonBlock({ leftRight, emphasisWords, isActive }: { 
  leftRight: [string, string]; 
  emphasisWords?: string[];
  isActive?: boolean;
}) {
  return (
    <div className={cn(
      "grid grid-cols-2 gap-4",
      isActive && "ring-2 ring-primary/50 rounded-lg"
    )}>
      <div className="p-4 rounded-lg bg-blue-500/10 border border-blue-500/20">
        <div className="flex items-center gap-2 mb-2">
          <div className="w-3 h-3 rounded-full bg-blue-500" />
          <span className="font-semibold text-blue-600 dark:text-blue-400">
            {renderWithEmphasis(leftRight[0], emphasisWords)}
          </span>
        </div>
      </div>
      <div className="p-4 rounded-lg bg-green-500/10 border border-green-500/20">
        <div className="flex items-center gap-2 mb-2">
          <div className="w-3 h-3 rounded-full bg-green-500" />
          <span className="font-semibold text-green-600 dark:text-green-400">
            {renderWithEmphasis(leftRight[1], emphasisWords)}
          </span>
        </div>
      </div>
    </div>
  );
}

/**
 * Equation/Formula layout: centered formula with visual emphasis
 */
function EquationBlock({ formula, emphasisWords, isActive }: { 
  formula: string; 
  emphasisWords?: string[];
  isActive?: boolean;
}) {
  return (
    <div className={cn(
      "flex items-center justify-center p-6 rounded-lg bg-gradient-to-r from-purple-500/10 to-indigo-500/10 border border-purple-500/20",
      isActive && "ring-2 ring-purple-500/50"
    )}>
      <div className="flex items-center gap-3">
        <Calculator className="h-5 w-5 text-purple-500" />
        <code className="text-lg font-mono font-semibold text-purple-600 dark:text-purple-400">
          {renderWithEmphasis(formula, emphasisWords)}
        </code>
      </div>
    </div>
  );
}

/**
 * Quote/Callout layout: highlighted important statement
 */
function QuoteBlock({ text, emphasisWords, isActive }: { 
  text: string; 
  emphasisWords?: string[];
  isActive?: boolean;
}) {
  return (
    <div className={cn(
      "relative pl-6 py-4 pr-4 rounded-r-lg bg-amber-500/10 border-l-4 border-amber-500",
      isActive && "ring-2 ring-amber-500/50"
    )}>
      <Quote className="absolute left-2 top-3 h-4 w-4 text-amber-500/50" />
      <p className="text-base italic font-medium text-amber-700 dark:text-amber-300">
        {renderWithEmphasis(text, emphasisWords)}
      </p>
    </div>
  );
}

/**
 * Callout layout: important insight or tip
 */
function CalloutBlock({ text, emphasisWords, isActive }: { 
  text: string; 
  emphasisWords?: string[];
  isActive?: boolean;
}) {
  return (
    <div className={cn(
      "flex items-start gap-3 p-4 rounded-lg bg-yellow-500/10 border border-yellow-500/20",
      isActive && "ring-2 ring-yellow-500/50"
    )}>
      <Lightbulb className="h-5 w-5 text-yellow-600 dark:text-yellow-400 flex-shrink-0 mt-0.5" />
      <p className="text-base">
        {renderWithEmphasis(text, emphasisWords)}
      </p>
    </div>
  );
}

/**
 * List layout: structured bullet points with checkmarks
 */
function ListBlock({ text, emphasisWords, isActive }: { 
  text: string; 
  emphasisWords?: string[];
  isActive?: boolean;
}) {
  // Parse text into list items (split by common delimiters)
  const items = text
    .split(/[;•\n]/)
    .map(s => s.trim())
    .filter(s => s.length > 0);

  if (items.length <= 1) {
    return <PlainBlock text={text} emphasisWords={emphasisWords} isActive={isActive} />;
  }

  return (
    <ul className={cn(
      "space-y-2 p-4 rounded-lg bg-muted/50",
      isActive && "ring-2 ring-primary/50"
    )}>
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2">
          <Check className="h-4 w-4 text-green-500 mt-1 flex-shrink-0" />
          <span className="text-base">
            {renderWithEmphasis(item, emphasisWords)}
          </span>
        </li>
      ))}
    </ul>
  );
}

/**
 * Plain layout: standard paragraph text
 */
function PlainBlock({ text, emphasisWords, isActive }: { 
  text: string; 
  emphasisWords?: string[];
  isActive?: boolean;
}) {
  return (
    <p className={cn(
      "text-base leading-relaxed p-3 rounded-lg transition-all duration-300",
      isActive && "bg-primary/10 ring-2 ring-primary/30"
    )}>
      {renderWithEmphasis(text, emphasisWords)}
    </p>
  );
}

/**
 * Main SlideContentBlock component
 * Renders content with AI-determined optimal layout
 */
export function SlideContentBlock({ 
  text, 
  layoutHint, 
  isActive = false,
  blockId,
  className 
}: ContentBlockProps) {
  const emphasisWords = layoutHint?.emphasis_words;

  // If no layout hint, render as plain text
  if (!layoutHint) {
    return (
      <div data-block-id={blockId} className={className}>
        <PlainBlock text={text} emphasisWords={emphasisWords} isActive={isActive} />
      </div>
    );
  }

  const renderBlock = () => {
    switch (layoutHint.type) {
      case 'flow':
        if (layoutHint.segments?.length) {
          return <FlowBlock segments={layoutHint.segments} emphasisWords={emphasisWords} isActive={isActive} />;
        }
        return <PlainBlock text={text} emphasisWords={emphasisWords} isActive={isActive} />;

      case 'comparison':
        if (layoutHint.left_right) {
          return <ComparisonBlock leftRight={layoutHint.left_right} emphasisWords={emphasisWords} isActive={isActive} />;
        }
        return <PlainBlock text={text} emphasisWords={emphasisWords} isActive={isActive} />;

      case 'equation':
        if (layoutHint.formula) {
          return <EquationBlock formula={layoutHint.formula} emphasisWords={emphasisWords} isActive={isActive} />;
        }
        return <PlainBlock text={text} emphasisWords={emphasisWords} isActive={isActive} />;

      case 'quote':
        return <QuoteBlock text={text} emphasisWords={emphasisWords} isActive={isActive} />;

      case 'callout':
        return <CalloutBlock text={text} emphasisWords={emphasisWords} isActive={isActive} />;

      case 'list':
        return <ListBlock text={text} emphasisWords={emphasisWords} isActive={isActive} />;

      default:
        return <PlainBlock text={text} emphasisWords={emphasisWords} isActive={isActive} />;
    }
  };

  return (
    <div data-block-id={blockId} className={className}>
      {renderBlock()}
    </div>
  );
}

export default SlideContentBlock;
