
ALTER TABLE public.company_profiles
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS zip text,
  ADD COLUMN IF NOT EXISTS state text,
  ADD COLUMN IF NOT EXISTS country text,
  ADD COLUMN IF NOT EXISTS organization_logo_url text,
  ADD COLUMN IF NOT EXISTS organization_linkedin_url text,
  ADD COLUMN IF NOT EXISTS organization_twitter_url text,
  ADD COLUMN IF NOT EXISTS organization_facebook_url text,
  ADD COLUMN IF NOT EXISTS organization_founded_year integer,
  ADD COLUMN IF NOT EXISTS organization_industry_keywords text[],
  ADD COLUMN IF NOT EXISTS contact_headline text,
  ADD COLUMN IF NOT EXISTS contact_photo_url text,
  ADD COLUMN IF NOT EXISTS contact_city text,
  ADD COLUMN IF NOT EXISTS contact_state text,
  ADD COLUMN IF NOT EXISTS contact_country text,
  ADD COLUMN IF NOT EXISTS contact_email_status text,
  ADD COLUMN IF NOT EXISTS contact_employment_history jsonb,
  ADD COLUMN IF NOT EXISTS contact_phone_numbers jsonb,
  ADD COLUMN IF NOT EXISTS contact_twitter_url text,
  ADD COLUMN IF NOT EXISTS funding_events jsonb,
  ADD COLUMN IF NOT EXISTS data_enrichment_level text DEFAULT 'basic',
  ADD COLUMN IF NOT EXISTS matching_skills text[];
